#Download base image 
FROM frolvlad/alpine-oraclejdk8:slim


#Expose ports
EXPOSE 8080:8080

#Copy jar files to current loacation
ADD Spring-Boot-Ex-0.0.1.jar boot.jar

#Define entry point command to execute
ENTRYPOINT ["java", "-jar" ,"boot.jar"]